# Generated by Django 5.0.6 on 2024-06-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_delete_preciounitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
