# Generated by Django 5.0.6 on 2024-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_producto_porcentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
